bot/urls.py
from django.urls import path
from . import views


urlpatterns = [
        path('', views.home, name='home'),
        path('login/', views.loginUser, name='login'),
        path('logout/', views.logoutUser, name='logout'),
        path('db/clear/', views.clear_db, name="Clear Database"),

        #Accounts Paths

        path('ac/', views.nl_accounts, name='nairaland-accounts'),
        path('ac/add/', views.NairalandAccountCreate.as_view(), name='add_nairaland-account'),
        path('ac/<int:pk>/', views.NairalandAccountDetail.as_view(), name='nairaland-account-detail'),
        path('ac/<int:pk>/edit/', views.NairalandAccountUpdate.as_view(), name='nairaland-account-update'),
        path('ac/<int:pk>/delete', views.NairalandAccountDelete.as_view(), name='nairaland-account-delete'),

        #Jobs Paths

        path('jobs/', views.jobs, name='jobs'),
        path('jobs/bj/add/', views.BoardJobCreate.as_view(), name='add_boardreplyjob'),
        path('jobs/bj/<int:pk>/', views.BoardJobDetail.as_view(), name='boardreplyjob-detail'),
        path('jobs/bj/<int:pk>/edit/', views.BoardJobUpdate.as_view(), name='boardreplyjob-update'),
        path('jobs/bj/<int:pk>/delete', views.BoardJobDelete.as_view(), name='boardreplyjob-delete'),
        path('jobs/td/add/', views.ThreadJobCreate.as_view(), name='add_threadreplyjob'),
        path('jobs/td/<int:pk>/', views.ThreadJobDetail.as_view(), name='threadreplyjob-detail'),
        path('jobs/td/<int:pk>/edit/', views.ThreadJobUpdate.as_view(), name='threadreplyjob-update'),
        path('jobs/td/<int:pk>/delete', views.ThreadJobDelete.as_view(), name='threadreplyjob-delete'),
        path('jobs/fp/add/', views.FrontPageMonitorJobCreate.as_view(), name='add_frontpagemonitorjob'),
        path('jobs/fp/<int:pk>/', views.FrontPageMonitorJobDetail.as_view(), name='frontpagemonitorjob-detail'),
        path('jobs/fp/<int:pk>/edit/', views.FrontPageMonitorJobUpdate.as_view(), name='frontpagemonitorjob-update'),
        path('jobs/fp/<int:pk>/delete', views.FrontPageMonitorJobDelete.as_view(), name='frontpagemonitorjob-delete'), 


        #Activate Jobs paths
        

        path('jobs/bj/<int:pk>/activate/', views.activateBjJob, name='activate-bj-job'),
        path('jobs/td/<int:pk>/activate/', views.activateTdJob, name='activate-td-job'),
        path('jobs/fp/<int:pk>/activate/', views.activateFpJob, name='activate-fp-job'),
         
               
        #Deactivate Jobs

        path('jobs/td/<int:pk>/deactivate/', views.deactivateTdJob, name='deactivate-td-job'),
        path('jobs/bj/<int:pk>/deactivate/', views.deactivateBjJob, name='deactivate-bj-job'),
        path('jobs/fp/<int:pk>/deactivate/', views.deactivateFpJob, name='deactivate-fp-job'),
         
          

      
        path('account/', views.account, name='account'),
        path('change_password/', views.changePassword, name='change pwd'),
        ]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bot.urls')),
    ]

bot/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse


ACCOUNT_TYPE = [
        ('st', 'Standard'),
        ('pr', 'Premium'),
        ('n', 'None'),
        ]


class NairalandAccount(models.Model):
    username = models.CharField(max_length=60)
    password = models.CharField(max_length=60)
    has_job = models.BooleanField(default=False)

    def __str__(self):
        return self.username


    def get_absolute_url(self):
        return reverse('nairaland-account-detail', kwargs = {'pk':self.pk})






class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    activated = models.BooleanField(default=False)
    account_type = models.CharField(max_length=2, choices=ACCOUNT_TYPE, default='n')
    license_key = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.username



class BoardReplyJob(models.Model):
    board_name = models.CharField(max_length=60)
    board_uri = models.CharField(max_length=200)
    reply = models.TextField()
    activated = models.BooleanField(default=False)
    nl_account_pk = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return f' {self.board_name} reply job'

    def get_absolute_url(self):
        return reverse('boardreplyjob-detail', kwargs = {'pk':self.pk})


class ThreadReplyJob(models.Model):
    thread_title = models.CharField(max_length=200)
    reply = models.TextField()
    topic_code = models.PositiveIntegerField()
    activated = models.BooleanField(default=False)
    nl_account_pk = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.thread_title


    def get_absolute_url(self):
        return reverse('threadreplyjob-detail', kwargs = {'pk':self.pk})



class FrontPageMonitorJob(models.Model):
    board_name = models.CharField(max_length=60, default="Frontpage")
    board_uri = models.CharField(max_length=200, default="https://www.nairaland.com/")
    reply = models.TextField()
    activated = models.BooleanField(default=False)
    nl_account_pk = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return f' {self.board_name} {self.pk} reply job'

    def get_absolute_url(self):
        return reverse('frontpagemonitorjob-detail', kwargs = {'pk':self.pk})


class DoneFPTopics(models.Model):
    topic = models.CharField(max_length = 11, unique=True)
    date = models.DateTimeField(unique=False)

class DoneBJTopics(models.Model):
    topic = models.CharField(max_length = 11)
    date = models.DateTimeField(unique=True)

class DoneTDTopics(models.Model):
    topic = models.CharField(max_length = 11, null=True)
    date = models.DateTimeField(unique=True)



@receiver(user_logged_in)
def createProfile(sender, user, request, **kwargs):
    try:
        if user.profile:
            pass
    except ObjectDoesNotExist:
        profile = Profile.objects.create(
                user=user,
                activated=False,
                account_type='n',)
        profile.save()

bot/views.py
from . import jobs as cron_jobs
from func_timeout import func_timeout, FunctionTimedOut
from django.shortcuts import (redirect, render, get_object_or_404)
from django.contrib.auth.decorators import (login_required)
from django.contrib.auth import (authenticate, login, logout)
from django.contrib import messages
from . import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import (reverse_lazy, reverse)
from django.views.generic.edit import (CreateView, UpdateView, DeleteView)
from django.views.generic.detail import DetailView
from django.http import HttpResponseRedirect
import datetime







def start_TdJob(login_details, thread_title, topic_code, thread_reply, thread_job, nl_account, nl_account_pk, minutes):
    try:
        job = func_timeout(26, cron_jobs.ThreadReplyJob_, args=(login_details, thread_title, topic_code, thread_reply))
    except FunctionTimedOut:
        raise FunctionTimedOut
    cron_jobs.scheduler.add_job(job.spam_thread, 'interval', minutes=int(minutes), id=nl_account_pk, replace_existing=True, max_instances=1)

    #Change has job value
    nl_account.has_job = True

    #Activate Job
    thread_job.activated = True
    thread_job.nl_account_pk = nl_account_pk
    nl_account.save()
    thread_job.save()




def start_BjJob(login_details, board_uri, board_reply, board_job, nl_account, nl_account_pk, minutes):
    try:
        job = func_timeout(26, cron_jobs.BoardReplyJob_, args=(login_details, board_uri, board_reply, int(minutes)))
    except FunctionTimedOut:
        raise FunctionTimedOut
    cron_jobs.scheduler.add_job(job.spam_board, 'interval', minutes=int(minutes), id=nl_account_pk)

    #Change has job value
    nl_account.has_job = True
    
    #Activate Job
    board_job.activated = True
    board_job.nl_account_pk = nl_account_pk
    nl_account.save()
    board_job.save()




def start_FpJob(login_details, frontpage_reply, frontpage_job, nl_account, nl_account_pk, seconds):
    try:
        job = func_timeout(26, cron_jobs.FrontPageMonitorJob_, args=(login_details, frontpage_reply))
    except FunctionTimedOut:
        raise FunctionTimedOut
    cron_jobs.scheduler.add_job(job.spam_frontpage, 'interval', seconds=int(seconds), id=nl_account_pk, replace_existing=True, max_instances=1)
    
    #Change has job value
    nl_account.has_job = True

    #Activate Job
    frontpage_job.activated = True
    frontpage_job.nl_account_pk = nl_account_pk
    nl_account.save()
    frontpage_job.save()




@login_required(login_url='/login')
def home(request):
    context = {
            'jobs':len(models.BoardReplyJob.objects.all()) + len(models.ThreadReplyJob.objects.all()) + len(models.FrontPageMonitorJob.objects.all()),
            'nl_accounts':len(models.NairalandAccount.objects.all()),
            'active_jobs':len(models.BoardReplyJob.objects.filter(activated=True)) + len(models.ThreadReplyJob.objects.filter(activated=True)) + len(models.FrontPageMonitorJob.objects.filter(activated=True)),
    }

    return render(request, 'bot/theme/index.html', context)



def loginUser(request):
    if request.method == 'POST':
        username = request.POST['username'].strip()
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('/')
    return render(request, 'bot/theme/login.html')

def logoutUser(request):
    logout(request)
    return redirect('/login/')



@login_required(login_url="/login")
def clear_db(request):
    models.DoneFPTopics.objects.all().delete()
    models.DoneTDTopics.objects.all().delete()
    models.DoneBJTopics.objects.all().delete()
    return redirect("/")


@login_required(login_url='/login/')
def account(request):
    profile = models.Profile.objects.get(user=request.user)
    return render(request, 'bot/theme/account.html', {'profile':profile})


@login_required(login_url='/login')
def changePassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        user = request.user
        user.set_password(password)
        user.save()
        messages.success(request, "Account password changed successfully.")
    return render(request, 'bot/theme/change.html')


@login_required(login_url="/login/")
def jobs(request):
    board_jobs = models.BoardReplyJob.objects.all()
    thread_jobs = models.ThreadReplyJob.objects.all()
    frontpage_jobs = models.FrontPageMonitorJob.objects.all()
    
    return render(request, 'bot/theme/jobs.html', {'board_jobs':board_jobs, 'thread_jobs':thread_jobs, 'frontpage_jobs':frontpage_jobs})



@login_required(login_url="/login/")
def nl_accounts(request):
    nairaland_accounts = models.NairalandAccount.objects.all()
    return render(request, 'bot/theme/ac.html', {'nairaland_accounts':nairaland_accounts})


@login_required(login_url="/login/")
def activateTdJob(request, pk):
    nl_accounts = models.NairalandAccount.objects.all()
    thread_job = get_object_or_404(models.ThreadReplyJob, ('pk',pk))
    thread_title = thread_job.thread_title
    topic_code = thread_job.topic_code
    thread_reply = thread_job.reply


    if request.method == 'POST':
        nl_account_pk = request.POST['nl_account_pk']
        nl_account = get_object_or_404(models.NairalandAccount, ('pk',nl_account_pk))
        #Check If Account has job
        if nl_account.has_job == True:
            messages.warning(request, "NL Account has a job!!!")
        else:
            minutes = request.POST['minutes']
            login_details = {'name':nl_account.username,'password':nl_account.password}
            try:
                start_TdJob(login_details, thread_title, topic_code, thread_reply, thread_job, nl_account, nl_account_pk, minutes)
                messages.success(request, "Activated Job!!!")
            except Exception as e:
                messages.warning(request, "Request timed out, please try again!!!")

            return redirect(reverse('threadreplyjob-detail', kwargs={'pk':thread_job.pk}))
        
    return render(request, 'bot/theme/td_activate.html', {'nl_accounts':nl_accounts, 'thread_job':thread_job})


@login_required(login_url="/login/")
def deactivateTdJob(request, pk):
    thread_job = get_object_or_404(models.ThreadReplyJob, ('pk',pk))
    if request.method == 'POST':
        nl_account_pk = request.POST['nl_account_pk']
        nl_account = get_object_or_404(models.NairalandAccount, ('pk',nl_account_pk))
        #Check If Account has job
        if nl_account.has_job == True:
            nl_account.has_job = False
            thread_job.activated = False
            thread_job.nl_account_pk= None
            try:
                cron_jobs.scheduler.remove_job(nl_account_pk)
            except:
                pass
            nl_account.save()
            thread_job.save()

        return HttpResponseRedirect(reverse('threadreplyjob-detail', kwargs={'pk':thread_job.pk}))
        





@login_required(login_url="/login/")
def activateBjJob(request, pk):
    nl_accounts = models.NairalandAccount.objects.all()
    board_job = get_object_or_404(models.BoardReplyJob, ('pk',pk))
    board_uri = board_job.board_uri
    board_reply = board_job.reply


    if request.method == 'POST':
        nl_account_pk = request.POST['nl_account_pk']
        nl_account = get_object_or_404(models.NairalandAccount, ('pk',nl_account_pk))
        #Check If Account has job
        if nl_account.has_job == True:
            messages.warning(request, "NL Account has a job!!!")
        else:
            minutes = request.POST['minutes']
            login_details = {'name':nl_account.username,'password':nl_account.password}
            try:
                start_BjJob(login_details, board_uri, board_reply, board_job, nl_account, nl_account_pk, minutes)
                messages.success(request, "Activated Job!!!")
            except Exception as e:
                raise e
                messages.warning(request, "Request timed out, please try again!!!")

            return HttpResponseRedirect(reverse('boardreplyjob-detail', kwargs={'pk':board_job.pk}))
        

        
    return render(request, 'bot/theme/bj_activate.html', {'nl_accounts':nl_accounts, 'board_job':board_job})


@login_required(login_url="/login/")
def deactivateBjJob(request, pk):
    board_job = get_object_or_404(models.BoardReplyJob, ('pk',pk))
    if request.method == 'POST':
        nl_account_pk = request.POST['nl_account_pk']
        nl_account = get_object_or_404(models.NairalandAccount, ('pk',nl_account_pk))
        #Check If Account has job
        if nl_account.has_job == True:
            nl_account.has_job = False
            board_job.activated = False
            board_job.nl_account_pk= None
            try:
                cron_jobs.scheduler.remove_job(nl_account_pk)
            except:
                pass
            nl_account.save()
            board_job.save()

        return HttpResponseRedirect(reverse('boardreplyjob-detail', kwargs={'pk':board_job.pk}))
        


@login_required(login_url="/login/")
def activateFpJob(request, pk):
    nl_accounts = models.NairalandAccount.objects.all()
    frontpage_job = get_object_or_404(models.FrontPageMonitorJob, ('pk',pk))
    frontpage_reply = frontpage_job.reply


    if request.method == 'POST':
        nl_account_pk = request.POST['nl_account_pk']
        nl_account = get_object_or_404(models.NairalandAccount, ('pk',nl_account_pk))
        #Check If Account has job
        if nl_account.has_job == True:
            messages.warning(request, "NL Account has a job!!!")
        else:
            seconds = request.POST['seconds']
            print(nl_account_pk)
            login_details = {'name':nl_account.username,'password':nl_account.password}
            try:
                start_FpJob(login_details, frontpage_reply, frontpage_job, nl_account, nl_account_pk, seconds)

bot/templates/bot/theme/account.html
{% extends 'bot/theme/index.html' %}

{% block main %}


 <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6">
	<div class="p-5">
		<div class="table-responsive">
		<table class="table">
		<tr>
			<th>Activated:</th>
			<td>{{ profile.activated }}</td>
		</tr>
		<tr>
			<th>Package Type:</th>
			<td>{{ profile.get_account_type_display }}</td>
		</tr>
		</table>
		</div>
	       </div>
              </div>
            </div>
	    	    </div>
	</div>
        </div>

      </div>

    </div>





{% endblock %}

bot/templates/bot/theme/account_form.html
{% extends 'bot/theme/index.html' %}

{% block main %}


<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
	<div class="p-5">
		<div class="col-auto">
	  <div class="text-center">
	    <h1 class="h4 text-gray-900 mb-4">Add NL Account</h1>
	  </div>
		</div>
	  <form class="user" action='/ac/add/' method='POST'>
		  {% csrf_token %}
				      <div class="col-auto">
                    <div class="form-group">
		      <input type="text" class="form-control" name="username" placeholder="Username" required>
                    </div>
	</div>
	<div class="col-auto">
                    <div class="form-group">
					      <input type="text" class="form-control" name="password" placeholder="Password" required>
		      	
                    </div>
	</div>

		    <div class="col-auto">
                <button type="submit" class="btn btn-primary btn-user btn-block">
                      Add
		</button>
		    </div>
                                      </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>



{% endblock %}

bot/templates/bot/theme/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Nairaland Bot - Dashboard</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>
<body id="page-top">


{% block content %}

{% endblock %}


  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

 </body>

</html>

bot/templates/bot/theme/bj_activate.html
{% extends 'bot/theme/index.html' %}

{% block main %}


<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
	<div class="p-5">
		<div class="col-auto">
	  <div class="text-center">
		  <p><strong>It may take a while</strong></p>
		  
		  <h1 class="h4 text-gray-900 mb-4">Activate  {{ board_job.board_name }} Job</h1>
	  </div>
		</div>
		<form class="user" action='/jobs/bj/{{ board_job.pk }}/activate/' method='POST'>
		  {% csrf_token %}
				      <div class="col-auto">
                    <div class="form-group">
					      <input type="number" class="form-control" name="minutes" placeholder="Minutes Interval" required>
		      	
                    </div>
	</div>
	<div class="col-auto">
                    <div class="form-group">
					      <select class="form-control" name="nl_account_pk" required>
			      {% for nl_account in nl_accounts %}
			      <option value="{{ nl_account.pk }}">{{ nl_account.username }}</option>
			      {% endfor %}
		      </select>
                    </div>
	</div>

		    <div class="col-auto">
                <button type="submit" class="btn btn-primary btn-user btn-block">
                      Activate
		</button>
		    </div>
                                      </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>



{% endblock %}

bot/templates/bot/theme/boardreplyjob_delete.html
{% extends 'bot/theme/index.html' %}

{% block main %}


 <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6">
	<div class="p-5">
		<form action="/jobs/bj/{{ object.pk }}/delete" method="POST">
			{% csrf_token %}
			Are you sure you want to delete <strong>{{ object.board_name }}</strong> job?
			<br/>
			<br/>
			<button class="btn btn-md btn-danger">Confirm</button>
		</form>
	</div>
      </div>
    </div>
  </div>
</div>
      </div>
    </div>





{% endblock %}

bot/templates/bot/theme/change.html
{% extends 'bot/theme/index.html' %}

{% block main %}


<div class="container">
	    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
      <div class="col-lg-6">
	<div class="p-5">
	  <div class="text-center">
	    <h1 class="h4 text-gray-900 mb-4">Change Password</h1>
	  </div>
	  <form class="user" action='/change_password/' method='POST'>
		  {% csrf_token %}
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name="password" placeholder="New password" required >
                    </div>
		                        <button type="submit" class="btn btn-primary btn-user btn-block">
                      Update
                    </a>
                                      </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>



{% endblock %}

bot/templates/bot/theme/fp_activate.html
{% extends 'bot/theme/index.html' %}

{% block main %}


<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
	<div class="p-5">
		<div class="col-auto">
	  <div class="text-center">
		  <p><strong>It may take a while</strong></p>
		  
		  <h1 class="h4 text-gray-900 mb-4">Activate  {{ frontpage_job.board_name }} Job</h1>
	  </div>
		</div>
		<form class="user" action='/jobs/fp/{{ frontpage_job.pk }}/activate/' method='POST'>
		  {% csrf_token %}
				      <div class="col-auto">
                    <div class="form-group">
			 
		      <input type="hidden" class="form-control" name="seconds" value="3" required>
		      	
                    </div>
	</div>
	<div class="col-auto">
                    <div class="form-group">
			 		      <select class="form-control" name="nl_account_pk" required>
			      {% for nl_account in nl_accounts %}
			      <option value="{{ nl_account.pk }}">{{ nl_account.username }}</option>
			      {% endfor %}
		      </select>
                    </div>
	</div>

		    <div class="col-auto">
                <button type="submit" class="btn btn-primary btn-user btn-block">
                      Activate
		</button>
		    </div>
                                      </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>



{% endblock %}

bot/templates/bot/theme/frontpagemonitorjob_delete.html
{% extends 'bot/theme/index.html' %}

{% block main %}


 <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6">
	<div class="p-5">
		<form action="/jobs/fp/{{ object.pk }}/delete" method="POST">
			{% csrf_token %}
			Are you sure you want to delete <strong>{{ object.board_name }}</strong> job?
			<br/>
			<br/>
			<button class="btn btn-md btn-danger">Confirm</button>
		</form>
	</div>
      </div>
    </div>
  </div>
</div>
      </div>
    </div>





{% endblock %}

bot/templates/bot/theme/frontpagemonitorjob_detail.html
{% extends 'bot/theme/index.html' %}

{% block main %}


 <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6">
	<div class="p-5">
		<div class="table-responsive">
		<table class="table">
		<tr>
			<th>Board Name:</th>
			<td>{{ object.board_name }} {{ object.pk }}</td>
		</tr>
		<tr>
			<th>Board Uri:</th>
			<td>{{ object.board_uri }}</td>
		</tr>
		<tr>
			<th>Reply:</th>
			<td>{{ object.reply }}</td>
		</tr>
	</table>
		</div>
	       </div>
              </div>
            </div>
	    <div class="row pb-5 pl-2 pr-2">
		    <div class="col-4">
			    <div class="text-center">
		
{% if not object.activated %}

				    <a class="btn btn-sm btn-success" href="/jobs/fp/{{ object.pk }}/activate">Activate</a>
				    {% else %}
				    <form method="POST" action="/jobs/fp/{{ object.pk }}/deactivate/">
					    {% csrf_token %}
					    <input type="hidden" name="nl_account_pk" value="{{ object.nl_account_pk }}">
					    <button class="btn btn-sm btn-danger" type="submit" >Deactivate</button>
				    </form>

				    {% endif %}



			    </div>
		    </div>
		    <div class="col-4">
			    <div class="text-center">
				    <a class="btn btn-sm btn-primary" href="/jobs/fp/{{ object.pk }}/edit">Edit Job</a>
			    </div>
		    </div>
		    <div class="col-4">
			    <div class="text-center">
				    <a class="btn btn-sm btn-danger" href="/jobs/fp/{{ object.pk }}/delete">Delete</a>
			    </div>
		    </div>


	    </div>
	</div>
        </div>

      </div>

    </div>





{% endblock %}

bot/templates/bot/theme/license.html
{% extends 'bot/theme/index.html' %}

{% block main %}


<div class="container">
	    <!-- Outer Row -->
    <div class="row justify-content-center">

	  <div class="text-center">
	    <h1 class="h4 text-gray-900 mb-4">Update License Key</h1>
	  </div>
	  <form class="user" action='/license/' method='POST'>
		  {% csrf_token %}
                    <div class="form-group">
			    <textarea class="form-control" rows="10" name="key" required>License key</textarea>
                    </div>
		                        <button type="submit" class="btn btn-primary btn-user btn-block">
                      Update
                    </a>
                                      </form>
                </div>
              </div>
            



{% endblock %}